### ISSUE TITLE
Money a double?

### ISSUE THREAD

**Issue by phase** [FiskFille/TransformersMod#1]
Making the Money a double would add more accuracy to the amount, which /may/ not be needed, but for currency conversions it may.

**Comment by Gegy** [comment]
Wat, there is no money in the mod. .-.

**Comment by phase** [comment]
Then you haven't looked at the mod...... There's a Money class used for Donations.....

**Comment by Gegy** [comment]
Oh, I made that class, I just realized that now. xD
