### ISSUE TITLE
My Character Is Showing When I Put the Armor

### ISSUE THREAD

**Issue by VinnieKS** [FiskFille/TransformersMod#113]
My Character Is Showing When I Put the Armor
How Can I fix IT?

**Comment by Gegy** [comment]
This is a know bug while you have optifine, smart moving, morph or galacticraft. If you have any of those, you should uninstall them

**Comment by VinnieKS** [comment]
Ok thnx ill try it gegy1000

**Comment by VinnieKS** [comment]
Does Galacticraft needs to be uninstalled??
+gegy1000

**Comment by Gegy** [comment]
Yes it does :)
