### ISSUE TITLE
1st person arm bug.

### ISSUE THREAD

**Issue by lyricalprimeboy** [FiskFille/TransformersMod#119]
I have the 0.5.1 version of the Transformers mod, and I am having troubles with the whole "seeing the arm of your robot in first person" thing. Instead of seeing the arm of the robot I am, I see my regular skin arm. Sometimes it works if I go to first person in vehicle mode and transform, but then it goes away of I go to 3rd person, transform to vehicle and back again, or open up my inventory. I tried re downloading it and messing with the config files, but nothing works. If it helps any, it is in a modpack I made on MultiMC with other mods such as Galacticraft and Optifine; I saw something about a bug with those mods not being compatible with the mod on the forums. Any help/ requests?

**Comment by aldebaran-01** [comment]
That's been happening to me too

**Comment by FiskFille** [comment]
GalactiCraft is usually the main mod causing issues alongside the Transformers mod. All OptiFine incompatibilities were fixed in 0.5.1, though.
