### ISSUE TITLE
i wanted to have the other jet mode not skystrike other one one with foot thrusters

### ISSUE THREAD

**Issue by redxop** [FiskFille/TransformersMod#121]
can you implement him back in the foot thrusters helped me out

**Comment by aldebaran-01** [comment]
cloudtrap is being reworked dude be patient

**Comment by redxop** [comment]
ok "dude" it was just a question  dont be a jackass

**Comment by Gegy** [comment]
We will be re-implementing him back in 0.6.0. :)
