### ISSUE TITLE
Bug? Inventory doesn't work

### ISSUE THREAD

**Issue by bnelson333** [FiskFille/TransformersMod#122]
Hi all, new here. I've just installed the Transformers mod and I found a really weird problem that I've never seen before with any other mod.

Background: multiplayer environment, MineOS server running Forge 1.7.10. Latest version of your mod, 0.5.1. I installed it on a fresh server, no other mods (not even optifine). When I launched it for the first time, I couldn't get inventory to open. It just wouldn't let me. Try remapping the keys, nothing.

So I thought maybe it just wont' work on multiplayer, so I try on single player. Fresh world, nothing. Same bug. But I found that in the controls options, if you reset your keys, now it works! It also worked on multiplayer. But it seems that you have to reset your key every "session". E.g. if you close the world and relog in later, you have to reset keys. Weird?

I don't know what it is, thought you might like to know about it.

**Comment by aldebaran-01** [comment]
Very wierd

**Comment by bnelson333** [comment]
UPDATE - not a bug. I didn't realize the mod created new action keys. One of those keys overlapped with the key I use for inventory, that's why it wasn't working. This is NOT a bug, sorry about that!
