### ISSUE TITLE
Black Screen (not a crash)

### ISSUE THREAD

**Issue by DeltaLightSoul** [FiskFille/TransformersMod#123]
When I equip a full set of armor for Purge,Vurp, or Subwoofer, everything goes black, except for any GUIs (menus, inventory, etc) I can still move and function normaly, i just can't see anything

![2015-06-04_01 14 38](https://cloud.githubusercontent.com/assets/12742549/7978108/6fbe58c2-0a57-11e5-8cf2-4673d3748243.png)

I equipped all four pieces, and then this happens.

![2015-06-04_01 15 20](https://cloud.githubusercontent.com/assets/12742549/7978115/83d7b31c-0a57-11e5-88f2-82ac2b71dc0f.png)

But i can still see my Inventory and other Menus.

![2015-06-04_01 15 31](https://cloud.githubusercontent.com/assets/12742549/7978133/a14142ec-0a57-11e5-99ed-c5ba25362e13.png)

**Comment by Gegy** [comment]
Have you tried uninstalling some of your other mods? They may be causing the problem. Uninstall everything but the Transformers Mod, see if it still gives you a black screen. If not install your other mods one by one and test each time. :)

**Comment by DeltaLightSoul** [comment]
@gegy1000 

I'm not sure why, but now everything is working fine. I did what you said and everything is compatible. I got rid of the SEUS shaders mod earlier today, and thought it might be the problem. I re-downloaded it, and installed it....No problems. Everything works fine. No black screens, no funky GUIs. It's weird and makes me look like a liar, but it's all true :/

**Comment by Gegy** [comment]
@DeltaLightSoul All that matters is that it now works :D
