### ISSUE TITLE
Transformers mod issue

### ISSUE THREAD

**Issue by XxNblitz** [FiskFille/TransformersMod#124]
every time i log into my world with this mod installed the internal servers shut down and i crash, i have tried re-downloading the mod and forge launcher as well as turn my computer off then back on. Im not sure weather it's because i'm using a mac but it's very annoying and it won't play.

**Comment by iLexiconn** [comment]
Can you post the crash log please?

**Comment by XxNblitz** [comment]
sorry just got the message the crash log is on my desktop and i am on
vacation when i get back i will sent the screen shots back sorry again just
got he message and thanks for replying

**Comment by Gegy** [comment]
Is this fixed?
