### ISSUE TITLE
Mod Forces Third Person View Distance

### ISSUE THREAD

**Issue by Peekofwar** [FiskFille/TransformersMod#125]
COMPATIBILITY ISSUE

MC Heli mod allows you to zoom in and out in third person with the "Page_Up" and "Page_Down" keys, but I've noticed that when I zoom out, there is a split second where it shows the correct distance, but it is then snapped back to a fixed distance, the default distance.

**Comment by Gegy** [comment]
There is no way around this unfortunately, we change the distance to our own one, and MC Heli is also changing the view distance.

**Comment by Peekofwar** [comment]
Is it not possible to just not force the view distance? Maybe you could force it only when it is necessary.

**Comment by FiskFille** [comment]
Problem here is that MCHeli forces the view distance, just as the TransformersMod does. If we were to make ours only change the view distance whenever necessary, MCHeli would just override it anyways.

**Comment by Peekofwar** [comment]
Why do you force the distance anyways? It's practically at the default.
