### ISSUE TITLE
Transformer Cloudtrap Flamethrower MP Crash

### ISSUE THREAD

**Issue by chudders1231** [FiskFille/TransformersMod#144]
Hey FiskFille, i am currently playing with the Transformers mod on a private server with just some friends which is part of a private modpack.

However i found out that when using Cloudtrap's Flamethrower, it pushes you from the server and puts a wierd error in the console. This does not crash the server by the way.

The console is a multicraft console so the error starts at the bottom and works its way up :/.
the crash:

16.10 18:14:39 [Server] INFO ... 12 more
16.10 18:14:39 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295) ~[mw.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[yz.class:?]
16.10 18:14:39 [Server] INFO at fiskfille.tf.common.item.ItemFlamethrower.onUsingTick(ItemFlamethrower.java:76) ~[ItemFlamethrower.class:?]
16.10 18:14:39 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Could not initialize class fiskfille.tf.client.particle.TFParticleType
16.10 18:14:39 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java) ~[mw.class:?]
16.10 18:14:39 [Server] INFO at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source) ~[ServerPlayerAPI.class:?]
16.10 18:14:39 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:349) ~[mw.class:?]
16.10 18:14:39 [Server] INFO net.minecraft.util.ReportedException: Ticking player
16.10 18:14:39 [Server] Server thread/WARN Failed to handle packet for /176.249.54.34:55998

**Comment by FiskFille** [comment]
We are aware of this issue, and it is already fixed in the latest patch. We just haven't released it yet.
