### ISSUE TITLE
Internal Servers crash upon opening worlds

### ISSUE THREAD

**Issue by a92b** [FiskFille/TransformersMod#147]
Okay, so I downloaded this (v 0.5.10) on my laptop, played and everything worked great. My brother downloads the same version and gets this crash log every time.

[crash-2015-12-26_21.15.08-client.txt](https://github.com/FiskFille/TransformersMod/files/72573/crash-2015-12-26_21.15.08-client.txt)

**Comment by FiskFille** [comment]
Does this crash still happen if you remove the Transformers Mod from the mods folder?

**Comment by a92b** [comment]
Okay, you might as well dismiss this issue; I tried without the mod and it still crashed. I'm going to try and reinstall Forge; maybe that'll fix it.

**Comment by a92b** [comment]
All set. Everything's been fixed, and thank you for helping.
