### ISSUE TITLE
My armor is with a bug that the armor is in my skin and when i transform my skin stay showed

### ISSUE THREAD

**Issue by gabriel-toledo** [FiskFille/TransformersMod#148]
it is with this bug and i can't play like this because when i am transformed my skin don't permiss me to see
![bug transformers](https://cloud.githubusercontent.com/assets/16600329/12183647/3ce3b0d4-b577-11e5-885d-62d976b0b830.png)

**Comment by Gegy** [comment]
What other mods do you have installed?

**Comment by Gegy** [comment]
If you have Optifine installed, this will happen. (This is fixed in the latest version of the mod, but not 0.4.x, which you have)

**Comment by HyperMan19680** [comment]
It also happens with mods like Galacticraft that modify the player's form or whatever, I dun recall what they called it.

**Comment by FiskFille** [comment]
Use version 0.5.0 or higher. This bug has been fixed in later versions.
