### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by runescapejon** [FiskFille/TransformersMod#149]
Hello I'm crashing with the latest version transformers mod 1.7.10-0.5.10 any idea how to fix this?
http://pastebin.com/TtQ7vTL1

**Comment by runescapejon** [comment]
here a better look at the crash http://hastebin.com/jobeyowaze.avrasm

**Comment by Gegy** [comment]
Unfortunately it looks like you have too many mods that are adding too many entities, Minecraft only has a limited amount of entities that can be added. :( There is no way we can fix this.

**Comment by runescapejon** [comment]
oh okay well i just found the problem too but i have just fix the issue thank you
