### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by flippednarwhale** [FiskFille/TransformersMod#151]
hello my game crashes when i wear a full set of armor please look at the crash below

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2/3/16 9:08 AM
Description: Rendering entity in world

java.lang.ClassCastException: fiskfille.tf.client.render.entity.CustomEntityRenderer cannot be cast to com.parzi.starwarsmod.rendering.helper.PSWMEntityRenderer
    at com.parzi.starwarsmod.handlers.ClientEventHandler.onRender(ClientEventHandler.java:237)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_417_ClientEventHandler_onRender_Pre.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:71)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
    at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
    at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:804)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1352)
    at fiskfille.tf.client.render.entity.CustomEntityRenderer.func_78480_b(CustomEntityRenderer.java:41)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.parzi.starwarsmod.handlers.ClientEventHandler.onRender(ClientEventHandler.java:237)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_417_ClientEventHandler_onRender_Pre.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:71)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)

-- Entity being rendered --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
    Entity ID: 59
    Entity Name: Cocodemon04
    Entity's Exact location: 178.67, 101.62, -68.44
    Entity's Block location: World: (178,101,-69), Chunk: (at 2,6,11 in 11,-5; contains blocks 176,0,-80 to 191,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0.00, -0.08, 0.00

-- Renderer details --
Details:
    Assigned renderer: fiskfille.tf.client.render.entity.player.RenderCustomPlayer@19b34a90
    Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Rotation: 0.0
    Delta: 1.0
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
    at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
    at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:804)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (265, 121). Absolute: (530, 463)
    Screen size: Scaled: (683, 353). Absolute: (1366, 706). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1352)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Cocodemon04'/59, l='MpServer', x=178.67, y=101.62, z=-68.44]]
    Chunk stats: MultiplayerChunkCache: 121, 130
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (166,64,-75), Chunk: (at 6,4,5 in 10,-5; contains blocks 160,0,-80 to 175,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 2095 game time, 2095 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 57 total; [EntitySkeleton['Skeleton'/4389, l='MpServer', x=132.50, y=23.00, z=-54.50], EntityBat['Bat'/3815, l='MpServer', x=184.75, y=61.10, z=-37.25], EntitySkeleton['Skeleton'/4390, l='MpServer', x=135.50, y=23.00, z=-55.50], EntitySkeleton['Skeleton'/63, l='MpServer', x=148.50, y=75.00, z=-10.50], EntityClientPlayerMP['Cocodemon04'/59, l='MpServer', x=178.67, y=101.62, z=-68.44], EntitySkeleton['Skeleton'/3305, l='MpServer', x=128.91, y=72.00, z=-43.50], EntityCreeper['Creeper'/65, l='MpServer', x=147.50, y=75.00, z=-14.50], EntityZombie['Zombie'/77, l='MpServer', x=245.50, y=51.00, z=-102.50], EntityZombie['Zombie'/3204, l='MpServer', x=126.50, y=85.00, z=-39.50], EntityCow['Cow'/3234, l='MpServer', x=212.50, y=68.00, z=10.50], EntityPig['Pig'/3690, l='MpServer', x=195.22, y=68.00, z=-2.22], EntityPig['Pig'/3691, l='MpServer', x=207.94, y=67.00, z=-9.16], EntityPig['Pig'/3689, l='MpServer', x=196.78, y=68.00, z=-3.78], EntityPig['Pig'/3692, l='MpServer', x=203.50, y=68.00, z=0.50], EntitySkeleton['Skeleton'/3138, l='MpServer', x=121.50, y=84.00, z=-37.50], EntitySkeleton['Skeleton'/3139, l='MpServer', x=180.50, y=63.00, z=-31.50], EntityZombie['Zombie'/3171, l='MpServer', x=168.34, y=17.00, z=-62.66], EntityZombie['Zombie'/3642, l='MpServer', x=110.50, y=81.00, z=-49.50], EntityCreeper['Creeper'/195, l='MpServer', x=159.50, y=77.00, z=-14.50], EntityTrail['unknown'/2664, l='MpServer', x=178.67, y=101.62, z=-68.44], EntityBat['Bat'/3617, l='MpServer', x=151.44, y=31.00, z=-57.65], EntityCreeper['Creeper'/234, l='MpServer', x=112.88, y=83.00, z=-44.25], EntityZombie['Zombie'/3601, l='MpServer', x=111.50, y=81.00, z=-48.50], EntityBat['Bat'/274, l='MpServer', x=184.60, y=62.67, z=-41.54], EntitySpider['Spider'/4093, l='MpServer', x=199.91, y=42.00, z=-113.60], EntityZombie['Zombie'/4094, l='MpServer', x=152.50, y=77.00, z=-15.50], EntitySkeleton['Skeleton'/4039, l='MpServer', x=257.50, y=35.00, z=-69.50], EntitySkeleton['Skeleton'/4042, l='MpServer', x=140.50, y=86.00, z=-39.50], EntitySkeleton['Skeleton'/4041, l='MpServer', x=141.50, y=86.00, z=-40.50], EntityBat['Bat'/4113, l='MpServer', x=247.50, y=52.00, z=-99.00], EntityBat['Bat'/4114, l='MpServer', x=249.84, y=52.18, z=-90.25], EntityBat['Bat'/4115, l='MpServer', x=162.88, y=35.10, z=-90.41], EntityItem['item.item.seeds'/2964, l='MpServer', x=191.25, y=95.13, z=-99.09], EntityCreeper['Creeper'/302, l='MpServer', x=176.50, y=27.00, z=-135.50], EntityBat['Bat'/4004, l='MpServer', x=247.28, y=52.00, z=-95.25], EntityWaypointContainer['unknown'/2525, l='MpServer', x=0.00, y=0.00, z=0.00], EntityBat['Bat'/4223, l='MpServer', x=180.53, y=25.07, z=-82.52], EntityZombie['Zombie'/4029, l='MpServer', x=159.50, y=77.00, z=-15.50], EntityZombie['Zombie'/4219, l='MpServer', x=245.50, y=46.00, z=-54.50], EntityZombie['Zombie'/4217, l='MpServer', x=246.50, y=46.00, z=-56.50], EntityEnderman['Enderman'/377, l='MpServer', x=180.50, y=70.00, z=-148.50], EntityEnderman['Enderman'/3962, l='MpServer', x=107.50, y=68.00, z=-11.50], EntitySpider['Spider'/3912, l='MpServer', x=125.00, y=33.00, z=-119.66], EntitySkeleton['Skeleton'/3913, l='MpServer', x=105.50, y=68.00, z=-10.50], EntitySkeleton['Skeleton'/4246, l='MpServer', x=134.50, y=23.00, z=-56.50], EntityBat['Bat'/4328, l='MpServer', x=180.72, y=61.00, z=-11.00], EntityZombie['Zombie'/3340, l='MpServer', x=230.50, y=24.00, z=-50.50], EntityBat['Bat'/4329, l='MpServer', x=182.03, y=61.00, z=-13.25], EntityBat['Bat'/4327, l='MpServer', x=181.41, y=61.00, z=-12.31], EntityItem['item.item.display_vehicle'/3874, l='MpServer', x=167.13, y=97.13, z=-65.06], EntityCreeper['Creeper'/3354, l='MpServer', x=237.00, y=22.00, z=-55.47], EntityZombie['Zombie'/4342, l='MpServer', x=134.50, y=23.00, z=-57.50], EntitySpider['Spider'/4340, l='MpServer', x=209.66, y=42.80, z=-114.75], EntityZombie['Zombie'/4339, l='MpServer', x=209.69, y=42.00, z=-118.69], EntityZombie['Zombie'/3845, l='MpServer', x=106.50, y=68.00, z=-14.50], EntityItem['item.item.seeds'/2419, l='MpServer', x=184.19, y=98.13, z=-92.50], EntitySkeleton['Skeleton'/485, l='MpServer', x=192.50, y=55.00, z=-57.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 310094960 bytes (295 MB) / 796614656 bytes (759 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_U_A4 30 mods loaded, 30 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PlayerAPI{1.1} [Player API](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FamiliarsAPI{1.7.10} [Familiars API](FamiliarsAPI-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    imsm{1.7.10} [Instant Massive Structures Mod]([1.7.10]InstantMassiveStructuresMod2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    animalbikes{1.7.10} [Animal Bikes](AnimalBikes_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AnimationAPI{1.2.3} [AnimationAPI](AnimationAPI-1.7.10-1.2.3 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chocolateQuest{0.0} [Chocolate Quest](chocolateQuest-1.7.10-BETA2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.7.10-3.0.1} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DefaultMobPack{1.7.10} [DefaultMobPack](FamiliarsDefaultMobPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtendedFamPack{1.7.10} [ExtendedFamPack](FamiliarsExtendedFamPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    farlanders{1.2b} [The Farlanders](farlanders-1.7.10-v1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraveStone{2.16.0} [GraveStone](GraveStone-2.16.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{4.0.0} [iChunUtil](iChun-Util-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    legends{1.3} [Legends Mod](Legends Core-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Morph{0.9.0} [Morph](Morphing-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MutantCreatures{1.4.7} [Mutant Creatures](Mutant-Creatures-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    starwarsmod{1.2.0} [Parzi's Star Wars Mod](Parzi's Star Wars Mod v1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    rivalrebels{1.7.10p} [Rival Rebels](rivalrebels-1.7.10p.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    sus{4.2.1} [Superheroes Unlimited Mod](Superheroes Unlimited Mod-1.7.10-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    susaddon{4.2.1} [Superheroes Unlimited Mod (Part 2)](Superheroes Unlimited Mod-1.7.10-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Sync{4.0.0} [Sync](Sync-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    transformers{${version}} [Transformers Mod](Transformers-1.7.10-0.5.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    voxelmap{1.7.10} [VoxelMap No Radar](Zans-MinimapNoRadar-Mod-1.7.10%281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3355, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by FiskFille** [comment]
**-- Head --
Stacktrace:
at com.parzi.starwarsmod.handlers.ClientEventHandler.onRender(ClientEventHandler.java:237)**

This is an issue with Parzi's Star Wars Mod, not the Transformers Mod. Please report it to Parzi, there's nothing we can do to fix this.

**Comment by flippednarwhale** [comment]
Thanks I don't need the mod I think is conflicting with Star Wars because Star Wars works fine with out it

**Comment by flippednarwhale** [comment]
I mean I don't need the Star Wars mod

**Comment by parzivail** [comment]
@flippednarwhale Download the most recent version, the issue had been long resolved

**Comment by flippednarwhale** [comment]
Thank you I will
