### ISSUE TITLE
Transformer mod 1.7.10

### ISSUE THREAD

**Issue by deKeetAruba** [FiskFille/TransformersMod#156]
I only can craft the tank. The other 3 transformers i cant craft, i have all the items, but the crafting table doesnt give the items. Do i need a special table for the other 3?

**Comment by deKeetAruba** [comment]
Also saved the game with Purge and 2 weapons on display tables. Opened the game few hours later, Purge gone, weapons gone.

**Comment by FiskFille** [comment]
What version of the mod are you using?
