### ISSUE TITLE
Black hud in vehicle form

### ISSUE THREAD

**Issue by PrimalUrsus** [FiskFille/TransformersMod#157]
Anytime I turn into a vehicle on any transformer I can't see any of the hud other than the default minecraft hud
![2016-03-26_11 29 37](https://cloud.githubusercontent.com/assets/18085212/14059783/160be802-f346-11e5-9382-745cb8dd048e.png)
![2016-03-26_11 28 57](https://cloud.githubusercontent.com/assets/18085212/14059784/160f3160-f346-11e5-8820-d1b36aaf96ed.png)
![2016-03-26_11 29 35](https://cloud.githubusercontent.com/assets/18085212/14059785/16137ec8-f346-11e5-98c2-48a084d5c916.png)

**Comment by FiskFille** [comment]
What other mods do you have installed?
Which version of Forge are you using?
Which version of the Transformers Mod are you using?

**Comment by PrimalUrsus** [comment]
The version of forge is 10.13.4.1614 for 1.7.10.
The mods I'm using is:
applied energistics
attachable grinder
Bibliocraft
Big Reactors
Carpenter's Blocks
Code chicken core
COFHCore
Decocraft
extra utilities
Food Plus
iChunUtil
Inventory tweaks
MineFactoryReloaded
MobAmputation
NEI Integration
NotEnoughItems
OpenBlocks
OpenModsLib
Optifine HD_U_D3
Project Red base, compact, fabrication, Integration, lighting,mechanical and world
Rival Rebels
Sync
Thermal Dynamics, Expansion and foundation 
Torched
ttcore
Xaeros Minimap
and of course both of you transformers mods (transformers 1.7.10-0.5.10 and transformersG1 1.7.10 1.0)
All the mods work and so far I haven't seen incompatibilities with the exception of the above. I have all the latest (to my knowledge) of the mods unless they've moved one version up :)

**Comment by PrimalUrsus** [comment]
I've also added waila

**Comment by FiskFille** [comment]
Try using version 10.13.4.1558 of Forge. When dealing with Forge, always use the version labeled as "Recommended" on their website, not "Latest".
[www,files.minecraftforge.net](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html)

**Comment by PrimalUrsus** [comment]
Unfortunately that still hasn't worked but it's no big deal really I'll just wait for the next update and hope it fixes it! :D

**Comment by Gegy** [comment]
It might be an incompatibility with Xaero's Minimap. Try disabling the map and see if the problem persists.

**Comment by PrimalUrsus** [comment]
I worked, to an extent, now it's only slightly greyed out although i think its an issue with the gui in minecraft itself not the mod

**Comment by Primal-Ursus** [comment]
I lost access to that particular account but I am the same Primal, the fix was removal of Project Red I guess the mod interrupts something
