### ISSUE TITLE
Player model is not being replaced

### ISSUE THREAD

**Issue by Tech0verlord** [FiskFille/TransformersMod#16]
For some reason, when I put the armor on, my player model does not get replaced by the armor model, and when I enter vehicle mode, my player model is still completely visible. The mods installed, along with their version numbers, are in the link below.

http://pastebin.com/s5smuTrF

Pics of the issue:

http://i.imgur.com/WJ4FhHU.png
http://i.imgur.com/z8VgFq3.png

**Comment by Tech0verlord** [comment]
Forgot to mention I'm using Minecraft Forge release 1.7.10-Forge10.13.2.1291

**Comment by Gegy** [comment]
Try using Forge 1.7.10-10.13.2.1230

**Comment by Gegy** [comment]
Oh, actually I see Galacticraft there, uninstall that.
