### ISSUE TITLE
Entering a ground bridge portal that leads into unloaded chunks "unloads" world

### ISSUE THREAD

**Issue by FiskFille** [FiskFille/TransformersMod#169]
The player becomes bugged and stuck in some sort of "empty world".
![screenshot_1](https://cloud.githubusercontent.com/assets/10811084/15451595/34a443fc-1fcb-11e6-8a6d-76e7cd7d5221.png)

**Comment by TerraVenator** [comment]
i didn't know the was a round bridge

**Comment by FiskFille** [comment]
Seems to be broken again in [0d4c1b8](https://github.com/FiskFille/TransformersMod/commit/0d4c1b87).
