### ISSUE TITLE
THe ARMOR Position

### ISSUE THREAD

**Issue by aimerite** [FiskFille/TransformersMod#171]
every time i look some where the entire body doesn't turn

**Comment by FiskFille** [comment]
What other mods do you have installed? Can you provide a screenshot of the issue?

**Comment by aimerite** [comment]
​
 Transformers-1.7.10-0.5.10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiQXpnendiT3dNUFU/view?usp=drive_web
​​
 VeinMiner-1.7.10_0.21.2.43.jar
https://drive.google.com/file/d/0BwSkQG7pPAjibWxFUjBpaDlBOUk/view?usp=drive_web
​​
 Thaumcraft-1.7.10-4.2.3.5.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiUzQzb3B6QWE3N2M/view?usp=drive_web
​​
 ThermalFoundation-[1.7.10]1.2.4-114.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiNTZqVmdtdzAxVkE/view?usp=drive_web
​​
 ThermalExpansion-[1.7.10]4.1.2-240.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiUW16eThvak1TRms/view?usp=drive_web
​​
 ThermalDynamics-[1.7.10]1.2.0-171.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiSlhnNTgzM1N5Rjg/view?usp=drive_web
​​
 TConstruct-1.7.10-1.8.8.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiSy1XRWJ4V3EzcEU/view?usp=drive_web
​​
 Streak-Mod-1.7.10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiUnktNjZ3YkF6SG8/view?usp=drive_web
​​
 SmartMoving-1.7.10-15.6.jar
https://drive.google.com/file/d/0BwSkQG7pPAjib1NPdURaSjBtWkU/view?usp=drive_web
​​
 SmartRender-1.7.10-2.1.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiTTMzejNOeW1DdUE/view?usp=drive_web
​​
 secretroomsmod-1.7.10-4.7.1.413.jar
https://drive.google.com/file/d/0BwSkQG7pPAjieVpFMGZxeUZqZlk/view?usp=drive_web
​​
 PlayerAPI-1.7.10-1.4.jar
https://drive.google.com/file/d/0BwSkQG7pPAjibFl4MTNHYTBUdEE/view?usp=drive_web
​​
 More-Health-Enhanced-Mod-1.7.10 (1).zip
https://drive.google.com/file/d/0BwSkQG7pPAjiTVhDdk5HYnlVdXc/view?usp=drive_web
​​
 NotEnoughItems-1.7.10-1.0.5.111-universal.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiMDJsM21ySll4blU/view?usp=drive_web
​​
 More-Bows-2-Mod-1.7.10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjib2VfV2JVZUsyajg/view?usp=drive_web
​​
 JourneyMap5.0.1_Unlimited_MC1.7.10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjicFVCcHVMS3NGdUk/view?usp=drive_web
​​
 Mantle-1.7.10-0.3.2b.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiSHBSVWNfZk5mMkU/view?usp=drive_web
​​
 iChunUtil-4.2.2.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiUGs0UXRFR3dGVHM/view?usp=drive_web
​​
 FamiliarsExtendedFamPack-1.7.10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjicXFadi1XZHotYkE/view?usp=drive_web
​​
 FamiliarsHerobrineFamPack-1.7.10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiaEpJa2VhMkdRTk0/view?usp=drive_web
​​
 extrautilities-1.2.12.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiQjNGNlNrQlJtQ0E/view?usp=drive_web
​​
 FamiliarsDefaultMobPack-1.7.10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiYmIwWXpOaWxYTFE/view?usp=drive_web
​​
 FamiliarsAPI-1.7.10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiZ2diUF92bmZFNnc/view?usp=drive_web
​​
 EnderIO-1.7.10-2.2.8.381.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiZExfbG52Y0Zsd2s/view?usp=drive_web
​​
 EnderStorage-1.7.10-1.4.7.36-universal.jar
https://drive.google.com/file/d/0BwSkQG7pPAjici1odkNlcVVKMkU/view?usp=drive_web
​​
 [1.7.10][SMP]DivineRPG-1.4.1.3.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiNzk4TVVIVTdiYXc/view?usp=drive_web
​​
 EnchantingPlus-1.7.10-3.0.2-d.jar
https://drive.google.com/file/d/0BwSkQG7pPAjic1BjWTFKM0Q4cEE/view?usp=drive_web
​​
 Elemental-Power-[1.7.10]-1.4.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiamhaRUpHV08tT3c/view?usp=drive_web
​​
 Draconic-Evolution-1.7.10-1.0.2d.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiWnN0eWRXZHUwNms/view?usp=drive_web
​​
 CoFHCore-[1.7.10]3.1.2-325.jar
https://drive.google.com/file/d/0BwSkQG7pPAjibTNfdDhvYTlkMHM/view?usp=drive_web
​​
 CodeChickenCore-1.7.10-1.0.7.46-universal.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiWFJ4Ty1RUXFvbWM/view?usp=drive_web
​​
 ChickenChunks-1.7.10-1.3.4.16-universal.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiSEZGUm80bnRyWDg/view?usp=drive_web
​​
 BrandonsCore-1.0.0.11.jar
https://drive.google.com/file/d/0BwSkQG7pPAjidjFGU2pkVFZTY2c/view?usp=drive_web
​​
 BotanicGarden-1.7.10-0.1.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiajZKdU5uRG9aaEE/view?usp=drive_web
​​
 Better-Furnaces-Mod-1.7.10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiblJWZG9SR2hLb28/view?usp=drive_web
​​
 Artifice-1.7.10-1.1.5R-399.jar
https://drive.google.com/file/d/0BwSkQG7pPAjibEpzal85NjJmWU0/view?usp=drive_web
​​
 appliedenergistics2-rv2-stable-10.jar
https://drive.google.com/file/d/0BwSkQG7pPAjidGVxbi13Zy0xSlE/view?usp=drive_web
​​
 1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar
https://drive.google.com/file/d/0BwSkQG7pPAjiRFpGYjgycXhIYmc/view?usp=drive_web
​​
 1.7.10-myfit-2.0.jar
https://drive.google.com/file/d/0BwSkQG7pPAjibzI1WFFnNHpqaWc/view?usp=drive_web

​

**Comment by FiskFille** [comment]
Smart Moving, Smart Render and Player API are some of the mods known to cause rendering issues when installed along the Transformers Mod. Try removing them and see what difference it makes.
