### ISSUE TITLE
can't download the mod

### ISSUE THREAD

**Issue by REVIN12** [FiskFille/TransformersMod#175]

**Comment by REVIN12** [comment]
I have watched 25  different videos onto download the mod but I can't

**Comment by FiskFille** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/10811084/15691668/6bc49e2e-278a-11e6-8866-2db306ce8b28.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/10811084/15691672/71c67784-278a-11e6-9852-0978d5a0f7c4.png)
