### ISSUE TITLE
the sourcecode is outdated

### ISSUE THREAD

**Issue by Maks2103** [FiskFille/TransformersMod#176]
Fisk, please upload a latest version of transformers mod's sourcecode

**Comment by Gegy** [comment]
This is the latest version of the sourcecode.

**Comment by Maks2103** [comment]
this is sourcecode of 0.5.10 version?

**Comment by FiskFille** [comment]
0.5.10 is the latest version.

**Comment by Maks2103** [comment]
i know that 0.5.10 is latest version, i ask wat's version of sourcecode, it's 0.5.10 too?

**Comment by Gegy** [comment]
Yes, it's 0.5.10.
