### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by Maks2103** [FiskFille/TransformersMod#177]
I have a question: how to build ground brige frame (portal)?

**Comment by Maks2103** [comment]
i'm already build a working portal.
here: screenshot of the builded portal - http://imgur.com/ma67bAe

**Comment by Gegy** [comment]
Please stop using 0.6.0.

**Comment by Maks2103** [comment]
why?
i using it's just for fun.

**Comment by Gegy** [comment]
There is a reason we haven't release it yet...
