### ISSUE TITLE
vehicle are above the block where i stand

### ISSUE THREAD

**Issue by ridler24** [FiskFille/TransformersMod#179]
when i am transformed into the vehicle, he is above the block where stand (in third person and this is very ugly) im in the last version of the mod and with no ADDON . can you please fix that ?

here some screenshots :100: 

![2016-09-04_20 23 14](https://cloud.githubusercontent.com/assets/21989362/18233078/2a6075bc-72de-11e6-9139-e56e5d646726.png)

![2016-09-04_20 23 57](https://cloud.githubusercontent.com/assets/21989362/18233081/32259f84-72de-11e6-8df5-57fcf163629c.png)

![2016-09-04_20 24 18](https://cloud.githubusercontent.com/assets/21989362/18233085/36e68894-72de-11e6-9817-12dad8c9c64f.png)

![2016-09-04_20 27 03](https://cloud.githubusercontent.com/assets/21989362/18233087/3e373cba-72de-11e6-96c0-2b7b96cab62f.png)
![2016-09-04_20 24 47](https://cloud.githubusercontent.com/assets/21989362/18233091/47d96130-72de-11e6-9659-fbb81674c48a.png)

here my installed mods :

![2016-09-04_20 25 06](https://cloud.githubusercontent.com/assets/21989362/18233096/57bf3980-72de-11e6-8ed9-f157a7808887.png)

i dont have problems with robots :

![2016-09-04_20 24 14](https://cloud.githubusercontent.com/assets/21989362/18233100/6737715c-72de-11e6-8f95-6978379829a4.png)

hope you can fix that...

Ridler24

**Comment by ridler24** [comment]
english not my first language,so please don't hurt me if i do faults

**Comment by Gegy** [comment]
Do you have a mod like More Player Models or Optifine installed?

**Comment by ridler24** [comment]
Flan's mod and fiskfille superheroes

**Comment by ridler24** [comment]
Flan's mod and fiskfille superheroes

**Comment by Gegy** [comment]
So just those mods? Nothing else?

**Comment by ridler24** [comment]
damage indicators and nothing else

**Comment by Gegy** [comment]
Superheroes seems the most likely cause of this problem. Do you have the latest version of Superheroes and the Transformers Mod?

**Comment by ridler24** [comment]
the latest version of all the mods

**Comment by Gegy** [comment]
@FiskFille

**Comment by ridler24** [comment]
i remove superheroes mod and transformers mod work perfectly

**Comment by ridler24** [comment]
it was because of the superheroes mod

**Comment by ridler24** [comment]
thanx for your help gegy1000

**Comment by FiskFille** [comment]
This is a known issue with the Superheroes mod. I will attempt to fix this as soon as I can.
