### ISSUE TITLE
Player rendering issue with MicDoodles galacticraft mod

### ISSUE THREAD

**Issue by dethgnome** [FiskFille/TransformersMod#18]
Although this is most likely a problem with galacticraft and not your transformers mod, when galacticraft is installed your player model doesn't change to the transformer. So when wearing your armor or while transformed your player is still there. Another problem I have been having with the transformers mod is I have not been able to find any transformium. I know that it is supposed to be rarer than diamonds, but after playing for about 48 hours over a few days I have found tons of diamonds, yet no transformium. I'm not entirely sure if this is just me being unlucky and not finding anything, or the ore not actually being generated.

**Comment by Gegy** [comment]
It's a problem with both mods, micdoodle Galacticraft mod is overriding the player model and so are we. The best thing to do for now is just uninstall Galacticraft or the Transformers Mod.

Also,  the best place to mine for transformium is Y:5 (bedrock)
