### ISSUE TITLE
[0.6.0 branch] NEI integration fails compilation

### ISSUE THREAD

**Issue by Maks2103** [FiskFille/TransformersMod#180]
Can't perform "gradlew runClient" or "gradlew buld" without removing "repository_folder"/src/main/java/fiskfille/tf/nei

**Comment by Maks2103** [comment]
@gegy1000 , can  you explain me, why an actual issue get closed before fixed? Or you already fix this issue but not yet commit this fix?

**Comment by FiskFille** [comment]
You're only experiencing this issue because you haven't set up your workspace correctly.

**Comment by Maks2103** [comment]
@FiskFille , i'm interested how i need to setup workspace "correctly"? I know only one way to setup it: "gradlew setupDecompWorkspace"

**Comment by Maks2103** [comment]
@FiskFille @gegy1000 , if it's my problems, why all builds after "Reimplemented NEI integration" marked with "failing" tag?

**Comment by Gegy** [comment]
We will not support you with this because we'd prefer if you didn't clone the 0.6.0 branch anyway.

**Comment by Maks2103** [comment]
@gegy1000 , i just want to help with bug-fixes, i just want to be useful.

**Comment by FiskFille** [comment]
We're good on out own, thank you.
