### ISSUE TITLE
[0.6.0 branch] transperent blocks

### ISSUE THREAD

**Issue by Maks2103** [FiskFille/TransformersMod#182]
reproduction steps: unkonown
screenshots: http://imgur.com/a/pEQgX

**Comment by FiskFille** [comment]
I can't reproduce the issue. Could you confirm whether it's fixed or not in the latest commit?

**Comment by Maks2103** [comment]
@FiskFille , yes, i can check it. starting right now!

**Comment by Maks2103** [comment]
@FiskFille , can't run client, can you help me?

log is here: http://pastebin.com/H6awEG69

**Comment by FiskFille** [comment]
Delete the fiskfille.tf.nei package.

**Comment by Maks2103** [comment]
@FiskFille , did you mean "nei" folder?

**Comment by FiskFille** [comment]
Yes

**Comment by Maks2103** [comment]
@FiskFille , i already did it, and still seeing this http://pastebin.com/H6awEG69

**Comment by FiskFille** [comment]
"Could not find tools.jar"
Can't you just run it in dev environment?

**Comment by Maks2103** [comment]
@FiskFille , i am a bad programmer and slightly don't know what command i need to use.
maybe gradlew runDevClient?

**Comment by FiskFille** [comment]
You can just open the workspace in Eclipse and run it from there

**Comment by Maks2103** [comment]
@FiskFille , can i use InteliJ IDEA instead of Eclipse?

**Comment by Gegy** [comment]
Yes, don't use Eclipse. :P

**Comment by Maks2103** [comment]
@FiskFille @gegy1000 , you both remind me about two my friends: Anton and Alexey. :)

**Comment by FiskFille** [comment]
Shush Gegy

**Comment by Maks2103** [comment]
@FiskFille , so, looks like the bug is disappeared, but with all the textures: http://imgur.com/a/wwhaF

**Comment by Maks2103** [comment]
@FiskFille , sorry, all the textures is allright! and this bug is fixed!

**Comment by FiskFille** [comment]
\o/
