### ISSUE TITLE
[0.6.0] lags with portal

### ISSUE THREAD

**Issue by Maks2103** [FiskFille/TransformersMod#183]
Portal causes lags when loading/unloading chunk wth portal designation.

**Comment by Maks2103** [comment]
aaaaand... again? what wrong this time?

**Comment by Gegy** [comment]
Same as last time. Stop. Posting. Issues. For. 0.6.0. Please.

**Comment by FiskFille** [comment]
Before you ask why - there's a reason 0.6.0 isn't released yet. It has loads of bugs, and we're very well aware of them.
