### ISSUE TITLE
Can't open download file in safari

### ISSUE THREAD

**Issue by Takhtay** [FiskFille/TransformersMod#185]
We are trying to download the Robot Mod but keep getting the error message.... Download failed. Safari cannot download this file. 
How can we get round this?
Thanks

**Comment by Gegy** [comment]
Where are you downloading it from?

**Comment by Takhtay** [comment]
Hi there.
We've payed money for it through the AppStore, there was actual email requested for download link to be mailed to. After I received the email by clicking on Download button I'm getting message "safari can not download this file"

Many thanks for looking into this

Serhiy

Sent from my iPhone

On 12 Oct 2016, at 0636, gegy1000 <notifications@github.com<mailto:notifications@github.com>> wrote:

Where are you downloading it from?

**Comment by Gegy** [comment]
Oh no... That is not official. This mod is free. You should download it from [here](http://download.fiskmods.com/?path=Mods/Transformers%20Mod/0.5.12/TransformersMod-1.7.10-0.5.12.jar).

**Comment by Gegy** [comment]
If you are trying to download for iOS, you can't. This mod is only for the PC game. I presume the thing you were trying to download is [this](https://itunes.apple.com/us/app/robot-mod-gun-for-minecraft/id1150957638), which is not official and I highly recommend you don't do.
