### ISSUE TITLE
Minecraft crashing after i've equipped cloudtrap armor on server

### ISSUE THREAD

**Issue by Magicalpizza** [FiskFille/TransformersMod#198]
I installed the transformers mod on my server and the fisrt thing i did was crafting the cloudtrap armor and using it for a litlle while. Then the next time i tried to play on the server my intire Minecraft crashed beacuse of the cloudtrap armor. 
Here is the log after Minecraft crashed.
http://paste.creeperhost.net/view/6db46e41#L6

**Comment by FiskFille** [comment]
This is all fixed in 0.6. Unfortunately, that also means there's nothing we can do to help until we get the rest of the update finished and released.
