### ISSUE TITLE
Liquid energon bug

### ISSUE THREAD

**Issue by Maks2103** [FiskFille/TransformersMod#205]
Fluiducts with energon being bugged after trying to intall servos, filters, etc. or reconfiguring with creascent hammer

**Comment by FiskFille** [comment]
What exactly is the problem?

**Comment by Maks2103** [comment]
Energon in fluiducts become white (i think that it means liquid's metadata corrupting) and each piece of pipe getting separated from another ones.

**Comment by FiskFille** [comment]
It might just mean that the fluiducts' developer has overlooked fluid colors. Either way, two energon liquids with different contents are treated by other mods as two completely different fluids, which can cause some funky stuff to happen. You should probably use the Energon Tank instead, which (along with all other blocks from the mod) automatically mix the energon to merge them into one.

**Comment by Maks2103** [comment]
@FiskFille , i have one last question for you in this topic: did you know, what is Thermal Expansion?

**Comment by FiskFille** [comment]
I know what it is, yes.

**Comment by Maks2103** [comment]
So, did you think that this is Thermal Expansion bug?
I just remember, that i previosly had same bug with other liquid, and maybe this is actualy Thermal Expansion's bug.
