### ISSUE TITLE
EMB/t Energon Transmitter Not working.

### ISSUE THREAD

**Issue by razorethan** [FiskFille/TransformersMod#211]
Hello, I have discovered an issue. On my server that I bought the Energon Transmitter and everything else that transfers EMB/t is not working. I have tried all of the versions and none of them seem to work on a server. I have double checked my files. They work perfectly fine on single player, its just on my server that it doesn't work. The main reason that I need this to work is because of the ground bridge and I really want to use it to get to the different dimensions in my modpack easier. Your time to help me would be much appreciated, it would help me and my friends a lot.

-razorethan

**Comment by Maks2103** [comment]
Did you using old world file? I faced same problem with old minecraft map (generated before 0.6 update)

**Comment by razorethan** [comment]
Yes is there a way to fix it so it works on my old world? Also sorry for the late response.

**Comment by Maks2103** [comment]
I don't know. I have same problem with my creative save.
