### ISSUE TITLE
Every time I try to start a mod it says it's crashed

### ISSUE THREAD

**Issue by 2403018** [FiskFille/TransformersMod#218]

**Comment by 2403018** [comment]
I think the crash report is The game crashed whilst exception in server tick loop Error: java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.doesOreNameExist(Ljava/lang/String;)Z

**Comment by FiskFille** [comment]
Update your version of Forge - you need version 1558 for Minecraft 1.7.10.
