### ISSUE TITLE
Vehicle mode zooms in and out and doesen't stop

### ISSUE THREAD

**Issue by ghost** [FiskFille/TransformersMod#225]
I do have optifine but I tried uninstalling it and it fixed my invisible hand but it still was glitched in vehicle mode. I need optifine for my frames so if you could find a solution for that as well it would be greatly appriciated as well.

**Comment by ghost** [comment]
Found the problem! Its an incombatibility with pazaris star wars mod. I still dont know about the hand though.

**Comment by Gegy** [comment]
Unfortunately we can't do anything about the hand, we've already worked on compatibility with Optifine but this is as far as we can go.

**Comment by FiskFille** [comment]
The OptiFine incompatibility is due to a relatively recent change in that mod. I use OptiFine_1.7.10_HD_U_D1, which doesn't have this issue.
