### ISSUE TITLE
Noob question re:game crash

### ISSUE THREAD

**Issue by GreenStripeMama** [FiskFille/TransformersMod#240]
Hey, I’m super new to Minecraft & mods, etc. so I might be clueless. I’m using Minecraft 1.14 and the “recommended Forge” and the Launch screen comes up fine, but when I add the Transformers mod we get a Game Crash before Launcher loads. Have I missed a step? Thanks!

**Comment by Gegy** [comment]
Hi! Unfortunately, this mod was only updated to Minecraft 1.7.10. It sadly can only be used for that version, due to the nature of Minecraft modding.
Another thing, Forge has not been released for 1.14 yet -- the highest version it supports as of yet is 1.13.2
