### ISSUE TITLE
Minecraft Launcher keeps crashing

### ISSUE THREAD

**Issue by ghost** [FiskFille/TransformersMod#242]
Hello! I am here because there is a bug with my Minecraft Launcher or the mod... Does anyone know the issue I have because I run Minecraft 1.12.2 Forge, and it keeps crashing whenever I pit the transformers mod in the Minecraft mods folder... I have som many mods installed so, I transferred all those mods and put them in my Minecraft 1.12.2 Forge Mods folder and the launcher still doesn't work. Can anyone solve this problem?

**Comment by FiskFille** [comment]
This mod is for 1.7.10, it won't work for 1.12.2.

**Comment by ghost** [comment]
Oh thanks
