### ISSUE TITLE
World is glitchy and when I put suit on its just green and sky blue.

### ISSUE THREAD

**Issue by Godmaster20906** [FiskFille/TransformersMod#250]
When I join in a world here what I see
![2023-01-09](https://user-images.githubusercontent.com/122239163/211439475-9fdd6432-17a3-40e9-b5b3-a22fc5b8f896.png)
![2023-01-09 (2)](https://user-images.githubusercontent.com/122239163/211439514-3d6cf946-27a2-4180-9322-9fd24962d6df.png)
![2023-01-09 (1)](https://user-images.githubusercontent.com/122239163/211439532-433e13c1-fc33-4121-aa7c-b691023c93ee.png)
Please help.

**Comment by Godmaster20906** [comment]
its the same with non flat worlds.

**Comment by FiskFille** [comment]
This is a problem not with the mod, nor even modded Minecraft, but one with Minecraft 1.7.10 itself. Modern graphics drivers no longer support some render functionality from that version of the game.

The only solution is to downgrade your graphics drivers, instructions for which can be found in the #mini-announcements channel in my Discord:
[https://discord.gg/MA7DuKm](https://discord.gg/MA7DuKm)
