### ISSUE TITLE
every armor is positioned wrongly,purge does not have texture

### ISSUE THREAD

**Issue by Stormstriker978** [FiskFille/TransformersMod#38]

**Comment by Gegy** [comment]
Could you post screenshots?

**Comment by Stormstriker978** [comment]
![2015-02-27_15 59 13](https://cloud.githubusercontent.com/assets/11177629/6409768/57bd5cf4-be9a-11e4-8fad-4a012b335e5c.png)

**Comment by Stormstriker978** [comment]
![2015-02-27_15 59 55](https://cloud.githubusercontent.com/assets/11177629/6409776/6a1ed86e-be9a-11e4-8054-baf65a1f95af.png)

**Comment by Gegy** [comment]
Firstly, you must uninstall Optifine to fix the player still showing when wearing armour. Secondly, the white Purge is due to you having a very old computer, this should be fixed in the next update. 
The Optifine bug is not fixable unfortunately.

**Comment by Stormstriker978** [comment]
ok thank you
