### ISSUE TITLE
In survival, Skystrike's Crossbow doesn't shoot but I have Energon Crystals   

### ISSUE THREAD

**Issue by xplozivegolem** [FiskFille/TransformersMod#54]
its annoying

**Comment by Gegy** [comment]
You have to be wearing the full skystrike suit.

**Comment by xplozivegolem** [comment]
I do, it's the only armor I wear

**Comment by FiskFille** [comment]
Do you have particles set to all or decreased?
Options > Video Settings > Particles
If particles is set to minimal, it will appear as though you aren't shooting.

**Comment by xplozivegolem** [comment]
Ok, Thanks. Sorry it took so long to reply, I've been busy with other things.

**Comment by Gegy** [comment]
So does it work? Also, you need energon crystal pieces, not the full crystals. :)
