### ISSUE TITLE
A way to turn Transformium Stone into Transformium

### ISSUE THREAD

**Issue by Gegy** [FiskFille/TransformersMod#83]

**Comment by Gegy** [comment]
It should be smeltable for 0.5.0 and when we add liquified energon, we should make a machine to refine it.

**Comment by Gegy** [comment]
It's now meltable, but for 0.6.0 there must be machinery for it.

**Comment by FiskFille** [comment]
Agreed

**Comment by aldebaran-01** [comment]
So basically a machine like thermal expansions fluid transposer
