### ISSUE TITLE
Inaccurate wheel sizes

### ISSUE THREAD

**Issue by FiskFille** [FiskFille/TransformersMod#91]
The wheels on Subwoofer are too big, and the wheels on Vurp are too small.

**Comment by Gegy** [comment]
You're not the modeller! :P

**Comment by FiskFille** [comment]
That doesn't matter, because this is an issue that can't be solved by a modeler. Making the wheels 2x2 is too small, 3x3 is too big. We would need to use GL11.glScalef()
